# Generated by Django 4.0 on 2022-06-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follow',
        ),
    ]
